-- =====================================================================
-- FoodHub - Exportacion de estructura de base de datos (schema only)
-- Generado desde el proyecto Supabase de origen para replicar en otro
-- proyecto Supabase. No incluye datos, solo estructura.
--
-- TABLAS CON SUPABASE REALTIME (postgres_changes):
--   - tables          → Admin (TablesManagement), Waiter (dashboard)
--   - orders          → Admin (Dashboard), Waiter (dashboard)
--   - order_items     → Admin (Dashboard), Waiter (dashboard)
--   - waiter_notifications → Waiter (dashboard)
--   - waiter_sessions → Admin (Dashboard + SessionsView)
--   - sales_history   → Admin (Dashboard)
-- =====================================================================

begin;

-- ---------------------------------------------------------------------
-- Extensiones requeridas
-- ---------------------------------------------------------------------
create extension if not exists "uuid-ossp" with schema extensions;
create extension if not exists "pgcrypto" with schema extensions;

-- ---------------------------------------------------------------------
-- Tablas
-- ---------------------------------------------------------------------

-- categories
create table if not exists public.categories (
  id integer generated by default as identity primary key,
  name character varying not null,
  slug character varying not null unique,
  description text default ''::text,
  display_order integer default 0,
  is_active boolean default true,
  created_at timestamp with time zone default timezone('utc'::text, now()),
  updated_at timestamp with time zone default timezone('utc'::text, now())
);

-- tables
create table if not exists public.tables (
  id integer generated by default as identity primary key,
  number integer,
  status character varying default 'available'::character varying,
  capacity integer not null,
  location character varying,
  created_at timestamp with time zone not null default timezone('utc'::text, now()),
  updated_at timestamp with time zone not null default timezone('utc'::text, now())
);

-- products
create table if not exists public.products (
  id integer generated by default as identity primary key,
  name character varying not null,
  description text,
  price integer not null,
  category character varying not null,
  image_url character varying,
  is_available boolean default true,
  preparation_time integer,
  meal_type text not null default 'both'::text check (meal_type in ('breakfast', 'lunch', 'both')),
  created_at timestamp with time zone not null default timezone('utc'::text, now()),
  updated_at timestamp with time zone not null default timezone('utc'::text, now()),
  rating numeric default 0.0,
  rating_count integer default 0,
  is_favorite boolean default false,
  extras jsonb default '[]'::jsonb
);

-- orders
create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  table_id integer not null references public.tables(id),
  customer_name character varying,
  status character varying default 'active'::character varying,
  total_amount numeric default 0,
  created_at timestamp with time zone not null default timezone('utc'::text, now()),
  updated_at timestamp with time zone not null default timezone('utc'::text, now())
);

-- order_items
create table if not exists public.order_items (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.orders(id) on delete cascade,
  product_id integer not null references public.products(id),
  product_name character varying not null,
  price numeric not null,
  quantity integer default 1,
  notes text,
  status character varying default 'ordered'::character varying,
  created_at timestamp with time zone not null default timezone('utc'::text, now()),
  updated_at timestamp with time zone not null default timezone('utc'::text, now()),
  cancelled_quantity integer default 0,
  course smallint not null default 1 check (course >= 1 and course <= 3)
);

-- waiter_notifications
create table if not exists public.waiter_notifications (
  id uuid primary key default gen_random_uuid(),
  table_id integer not null references public.tables(id),
  order_id uuid references public.orders(id),
  type character varying not null,
  message text not null,
  status character varying default 'pending'::character varying,
  created_at timestamp with time zone not null default timezone('utc'::text, now()),
  updated_at timestamp with time zone default timezone('utc'::text, now()),
  payment_method character varying,
  tip_amount numeric default 0
);

-- sales_history
create table if not exists public.sales_history (
  id uuid primary key default gen_random_uuid(),
  table_id integer not null references public.tables(id),
  table_number integer not null,
  customer_name character varying,
  total_amount numeric not null default 0,
  order_count integer not null default 0,
  item_count integer not null default 0,
  created_at timestamp with time zone not null default timezone('utc'::text, now()),
  closed_at timestamp with time zone not null default timezone('utc'::text, now()),
  payment_method character varying
);

-- sales_items
create table if not exists public.sales_items (
  id uuid primary key default gen_random_uuid(),
  sale_id uuid not null references public.sales_history(id) on delete cascade,
  product_name character varying not null,
  price numeric not null,
  quantity integer not null default 1,
  subtotal numeric not null,
  notes text
);

-- customer_feedback
create table if not exists public.customer_feedback (
  id uuid primary key default gen_random_uuid(),
  table_id text not null,
  customer_name text not null,
  rating integer not null check (rating >= 1 and rating <= 5),
  comment text,
  order_count integer not null,
  total_amount numeric not null,
  created_at timestamp with time zone default now(),
  feedback_type text not null default 'general' check (feedback_type in ('general', 'product')),
  product_id integer,
  product_name character varying
);

-- tips
create table if not exists public.tips (
  id uuid primary key default gen_random_uuid(),
  order_id uuid,
  table_id integer not null references public.tables(id) on delete cascade,
  customer_name text not null,
  amount numeric not null default 0,
  payment_method text,
  waiter_id uuid references public.users(id) on delete set null,
  created_at timestamp with time zone not null default now()
);

-- users: cuentas de staff (admin / waiter / super_admin) vinculadas a auth.users.
-- El rol de autorizacion vive en auth.users.raw_app_meta_data (JWT app_metadata),
-- no en esta tabla, para permitir checks de rol sin round-trip a public.users.
create table if not exists public.users (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null unique,
  name text not null,
  role text not null check (role in ('super_admin', 'admin', 'waiter')),
  pin_code char(4),
  is_active boolean not null default true,
  created_at timestamp with time zone not null default timezone('utc'::text, now()),
  updated_at timestamp with time zone not null default timezone('utc'::text, now()),
  constraint users_pin_code_format check (pin_code is null or pin_code ~ '^[0-9]{4}$')
);

-- app_settings: feature flags opt-in/opt-out configurables desde el admin panel
-- Soporta boolean (toggles) y text (time, select).
-- Lectura publica (el customer sin login necesita leer los flags),
-- escritura solo admin/super_admin.
create table if not exists public.app_settings (
  key text primary key,
  value text not null default 'false',
  updated_at timestamp with time zone not null default timezone('utc', now())
);

-- waiter_sessions: rastreo de turno por mesero para cierre y distribucion de propinas
create table if not exists public.waiter_sessions (
  id uuid primary key default gen_random_uuid(),
  waiter_id uuid not null references public.users(id) on delete cascade,
  waiter_name text not null,
  started_at timestamptz not null default now(),
  ended_at timestamptz,
  total_sales numeric not null default 0,
  created_at timestamptz not null default now()
);

-- cash_reports: sesion de caja abierta/cerrada (patron started_at/ended_at,
-- igual que waiter_sessions). "Abierta" = closed_at is null. Snapshot de
-- ventas/propinas del periodo [opened_at, closed_at] calculado al cerrar.
create table if not exists public.cash_reports (
  id uuid primary key default gen_random_uuid(),
  report_number integer generated always as identity,
  opened_at timestamp with time zone not null default now(),
  closed_at timestamp with time zone,

  opening_cash numeric not null default 0,
  counted_cash numeric,
  notes text,

  cash_sales numeric not null default 0,
  terminal_sales numeric not null default 0,
  usd_sales numeric not null default 0,
  mixed_sales numeric not null default 0,
  total_sales numeric not null default 0,

  cash_tips numeric not null default 0,
  terminal_tips numeric not null default 0,
  usd_tips numeric not null default 0,
  mixed_tips numeric not null default 0,
  total_tips numeric not null default 0,

  paid_accounts_count integer not null default 0,
  average_ticket numeric not null default 0,
  subtotal numeric not null default 0,
  tax_amount numeric not null default 0,

  expected_cash numeric not null default 0,
  cash_difference numeric not null default 0,

  opened_by uuid references public.users(id) on delete set null,
  closed_by uuid references public.users(id) on delete set null,
  created_at timestamp with time zone not null default now()
);

comment on column public.cash_reports.mixed_sales is 'Informativo solamente: no se incluye en expected_cash porque no se guarda el desglose efectivo/tarjeta de un pago mixed.';

-- ---------------------------------------------------------------------
-- Indices adicionales (fuera de PK/UNIQUE ya creados por las tablas)
-- ---------------------------------------------------------------------
create index if not exists tips_created_at_idx on public.tips using btree (created_at);
create index if not exists tips_table_id_idx on public.tips using btree (table_id);
create index if not exists tips_waiter_id_idx on public.tips using btree (waiter_id);

create index if not exists waiter_sessions_waiter_id_idx on public.waiter_sessions (waiter_id);
create index if not exists waiter_sessions_started_at_idx on public.waiter_sessions (started_at);

-- Unico PIN activo a la vez: permite reciclar el PIN de un waiter desactivado.
create unique index if not exists users_pin_code_unique_idx
  on public.users (pin_code)
  where pin_code is not null and is_active = true;
create index if not exists users_role_idx on public.users (role);

-- Solo una caja abierta a la vez.
create unique index if not exists cash_reports_single_open_idx
  on public.cash_reports ((closed_at is null))
  where closed_at is null;

-- ---------------------------------------------------------------------
-- Funciones
-- ---------------------------------------------------------------------
create or replace function public.update_updated_at_column()
returns trigger
language plpgsql
as $function$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$function$;

drop trigger if exists set_users_updated_at on public.users;
create trigger set_users_updated_at
  before update on public.users
  for each row execute function public.update_updated_at_column();

drop trigger if exists set_app_settings_updated_at on public.app_settings;
create trigger set_app_settings_updated_at
  before update on public.app_settings
  for each row execute function public.update_updated_at_column();

-- Lee app_metadata.role directo del JWT (sin consultar public.users -> sin recursion RLS)
create or replace function public.current_role()
returns text
language sql
stable
set search_path = ''
as $function$
  select coalesce((auth.jwt() -> 'app_metadata' ->> 'role'), '');
$function$;

-- ---------------------------------------------------------------------
-- Row Level Security
-- ---------------------------------------------------------------------
alter table public.categories enable row level security;
alter table public.tables enable row level security;
alter table public.products enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;
alter table public.waiter_notifications enable row level security;
alter table public.sales_history enable row level security;
alter table public.sales_items enable row level security;
alter table public.customer_feedback enable row level security;
alter table public.tips enable row level security;
alter table public.users enable row level security;
alter table public.waiter_sessions enable row level security;
alter table public.app_settings enable row level security;
alter table public.cash_reports enable row level security;

drop policy if exists "Allow all for all roles" on public.categories;
create policy "Allow all for all roles" on public.categories
  for all to public using (true) with check (true);

drop policy if exists "Allow all for tables" on public.tables;
create policy "Allow all for tables" on public.tables
  for all to public using (true);

drop policy if exists "Allow all for products" on public.products;
create policy "Allow all for products" on public.products
  for all to public using (true);

drop policy if exists "Allow all for orders" on public.orders;
create policy "Allow all for orders" on public.orders
  for all to public using (true);

drop policy if exists "Allow all for order_items" on public.order_items;
create policy "Allow all for order_items" on public.order_items
  for all to public using (true);

drop policy if exists "Allow all for notifications" on public.waiter_notifications;
create policy "Allow all for notifications" on public.waiter_notifications
  for all to public using (true);

drop policy if exists "Policy with security definer functions" on public.sales_history;
create policy "Policy with security definer functions" on public.sales_history
  for all to public using (true);

drop policy if exists "Policy with security definer functions" on public.sales_items;
create policy "Policy with security definer functions" on public.sales_items
  for all to public using (true);

drop policy if exists "feedback" on public.customer_feedback;
create policy "feedback" on public.customer_feedback
  for all to public using (true);

drop policy if exists "tips_select_all" on public.tips;
create policy "tips_select_all" on public.tips
  for select to public using (true);

drop policy if exists "tips_insert_all" on public.tips;
create policy "tips_insert_all" on public.tips
  for insert to public with check (true);

drop policy if exists "tips_update_all" on public.tips;
create policy "tips_update_all" on public.tips
  for update to public using (true);

-- users: unica tabla con RLS real por rol (el resto queda "allow all" por ahora)
drop policy if exists "users_select" on public.users;
create policy "users_select" on public.users
  for select to authenticated
  using (id = auth.uid() or public.current_role() in ('admin', 'super_admin'));

drop policy if exists "users_insert" on public.users;
create policy "users_insert" on public.users
  for insert to authenticated
  with check (public.current_role() in ('admin', 'super_admin'));

drop policy if exists "users_update" on public.users;
create policy "users_update" on public.users
  for update to authenticated
  using (public.current_role() in ('admin', 'super_admin'))
  with check (public.current_role() in ('admin', 'super_admin'));

drop policy if exists "users_delete" on public.users;
create policy "users_delete" on public.users
  for delete to authenticated
  using (public.current_role() in ('admin', 'super_admin'));

drop policy if exists "Allow all for waiter_sessions" on public.waiter_sessions;
create policy "Allow all for waiter_sessions" on public.waiter_sessions
  for all to public using (true);

drop policy if exists "Allow all for cash_reports" on public.cash_reports;
create policy "Allow all for cash_reports" on public.cash_reports
  for all to public using (true);

-- app_settings: lectura publica (customer sin login la necesita), escritura solo admin
drop policy if exists "app_settings_select_public" on public.app_settings;
create policy "app_settings_select_public" on public.app_settings
  for select to public using (true);

drop policy if exists "app_settings_write_admin" on public.app_settings;
create policy "app_settings_write_admin" on public.app_settings
  for all to authenticated
  using (public.current_role() in ('admin', 'super_admin'))
  with check (public.current_role() in ('admin', 'super_admin'));

-- ---------------------------------------------------------------------
-- Realtime publication
-- ---------------------------------------------------------------------
do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'tables'
  ) then
    alter publication supabase_realtime add table public.tables;
  end if;

  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'orders'
  ) then
    alter publication supabase_realtime add table public.orders;
  end if;

  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'order_items'
  ) then
    alter publication supabase_realtime add table public.order_items;
  end if;

  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'waiter_notifications'
  ) then
    alter publication supabase_realtime add table public.waiter_notifications;
  end if;
end $$;

-- ---------------------------------------------------------------------
-- Migraciones aplicadas
-- ---------------------------------------------------------------------

-- 2026-07-20: add_meal_type_to_products
-- Agrega columna meal_type a products para controlar visibilidad por horario
alter table public.products add column if not exists meal_type text not null default 'both'::text
  check (meal_type in ('breakfast', 'lunch', 'both'));

update public.products set meal_type = 'breakfast' where category = 'Breakfast' and meal_type = 'both';
update public.products set meal_type = 'lunch' where category in ('Lunch', 'Dinner') and meal_type = 'both';
update public.products set meal_type = 'both' where category in ('Combos', 'Drinks', 'Refill') and meal_type = 'both';

-- 2026-07-20: Alter app_settings.value a text para soportar string ademas de boolean
alter table public.app_settings alter column value type text using value::text;
alter table public.app_settings alter column value set not null;
alter table public.app_settings alter column value set default 'false'::text;

-- 2026-07-21: add_course_to_order_items
-- Agrega columna course a order_items para tiempos de comida (1=Primer, 2=Segundo, 3=Tercer)
alter table public.order_items add column if not exists course smallint not null default 1
  check (course >= 1 and course <= 3);

-- 2026-07-21: add_feedback_type_to_customer_feedback
-- Distingue reseñas generales de reseñas por producto en la encuesta post-pago
alter table public.customer_feedback
  add column if not exists feedback_type text not null default 'general' check (feedback_type in ('general', 'product'));
alter table public.customer_feedback
  add column if not exists product_id integer;
alter table public.customer_feedback
  add column if not exists product_name character varying;

-- 2026-07-21: add_waiter_sessions
-- Tabla + columna waiter_id en tips + indices + seed ya incluidos arriba.
-- Migration aplicada: creacion de waiter_sessions, tips.waiter_id, indices y seed tip_distribution.
-- 2026-07-21: add_tips_waiter_id
-- 2026-07-21: add_waiter_sessions_indexes

-- 2026-07-22: create_cash_reports_table
-- Tabla cash_reports (corte de caja diario) ya incluida arriba.

-- 2026-07-22: cash_reports_open_close_flow
-- Rediseno de "un reporte por fecha con inputs manuales" a sesion abierta/cerrada
-- (opened_at/closed_at, "abierta" = closed_at is null). Se eliminan report_date,
-- cash_deposits, cash_withdrawals (sin dato real detras); created_by -> opened_by;
-- se agrega closed_by. Cambios ya incluidos en la definicion de la tabla arriba.

-- ---------------------------------------------------------------------
-- Seed data: feature flags iniciales
-- ---------------------------------------------------------------------
insert into public.app_settings (key, value)
values ('product_notes_enabled', 'false')
on conflict (key) do nothing;

insert into public.app_settings (key, value)
values ('product_ratings_enabled', 'false')
on conflict (key) do nothing;

insert into public.app_settings (key, value)
values ('breakfast_end_hour', '11:00')
on conflict (key) do nothing;

insert into public.app_settings (key, value)
values ('printing_enabled', 'false')
on conflict (key) do nothing;

insert into public.app_settings (key, value)
values ('default_check_ui', 'modern')
on conflict (key) do nothing;

insert into public.app_settings (key, value)
values ('close_table_pin', '1234')
on conflict (key) do nothing;

insert into public.app_settings (key, value)
values ('tip_distribution', '{"Barra":1.2,"Cocina":3.0,"Garrotero":0,"Capitan":0,"Staff":1.0,"Caja":1.2,"Empaque":0}')
on conflict (key) do nothing;

-- ---------------------------------------------------------------------
-- Storage: buckets
-- ---------------------------------------------------------------------
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types, avif_autodetection)
values
  ('product-images', 'product-images', true, null, null, false),
  ('logo', 'logo', true, null, null, false),
  ('cover-image', 'cover-image', true, null, null, false)
on conflict (id) do nothing;

-- ---------------------------------------------------------------------
-- Storage: policies
-- ---------------------------------------------------------------------
drop policy if exists "Enable read access for all users" on storage.buckets;
create policy "Enable read access for all users" on storage.buckets
  for select to public using (true);

drop policy if exists "Enable read access for all users" on storage.objects;
create policy "Enable read access for all users" on storage.objects
  for insert to public with check (true);

drop policy if exists "Permitir lectura pública de logos" on storage.objects;
create policy "Permitir lectura pública de logos" on storage.objects
  for select to public using (bucket_id = 'logo'::text);

drop policy if exists "Permitir inserción de logos para usuarios autenticados" on storage.objects;
create policy "Permitir inserción de logos para usuarios autenticados" on storage.objects
  for insert to authenticated with check (bucket_id = 'logo'::text);

drop policy if exists "Permitir actualización de logos para usuarios autenticados" on storage.objects;
create policy "Permitir actualización de logos para usuarios autenticados" on storage.objects
  for update to authenticated using (bucket_id = 'logo'::text);

drop policy if exists "Permitir eliminación de logos para usuarios autenticados" on storage.objects;
create policy "Permitir eliminación de logos para usuarios autenticados" on storage.objects
  for delete to authenticated using (bucket_id = 'logo'::text);

drop policy if exists "Permitir lectura publica de cover-image" on storage.objects;
create policy "Permitir lectura publica de cover-image" on storage.objects
  for select to public using (bucket_id = 'cover-image'::text);

drop policy if exists "Permitir insercion de cover-image para usuarios autenticados" on storage.objects;
create policy "Permitir insercion de cover-image para usuarios autenticados" on storage.objects
  for insert to authenticated with check (bucket_id = 'cover-image'::text);

drop policy if exists "Permitir actualizacion de cover-image para usuarios autenticados" on storage.objects;
create policy "Permitir actualizacion de cover-image para usuarios autenticados" on storage.objects
  for update to authenticated using (bucket_id = 'cover-image'::text);

drop policy if exists "Permitir eliminacion de cover-image para usuarios autenticados" on storage.objects;
create policy "Permitir eliminacion de cover-image para usuarios autenticados" on storage.objects
  for delete to authenticated using (bucket_id = 'cover-image'::text);

commit;
