-- =====================================================================
-- FoodHub - Exportacion de estructura de base de datos (schema only)
-- Generado desde el proyecto Supabase de origen para replicar en otro
-- proyecto Supabase. No incluye datos, solo estructura.
-- =====================================================================

begin;

-- ---------------------------------------------------------------------
-- Extensiones requeridas
-- ---------------------------------------------------------------------
create extension if not exists "uuid-ossp" with schema extensions;
create extension if not exists "pgcrypto" with schema extensions;

-- ---------------------------------------------------------------------
-- Tablas
-- ---------------------------------------------------------------------

-- categories
create table if not exists public.categories (
  id integer generated by default as identity primary key,
  name character varying not null,
  slug character varying not null unique,
  description text default ''::text,
  display_order integer default 0,
  is_active boolean default true,
  created_at timestamp with time zone default timezone('utc'::text, now()),
  updated_at timestamp with time zone default timezone('utc'::text, now())
);

-- tables
create table if not exists public.tables (
  id integer generated by default as identity primary key,
  number integer,
  status character varying default 'available'::character varying,
  capacity integer not null,
  location character varying,
  created_at timestamp with time zone not null default timezone('utc'::text, now()),
  updated_at timestamp with time zone not null default timezone('utc'::text, now())
);

-- products
create table if not exists public.products (
  id integer generated by default as identity primary key,
  name character varying not null,
  description text,
  price integer not null,
  category character varying not null,
  image_url character varying,
  is_available boolean default true,
  preparation_time integer,
  created_at timestamp with time zone not null default timezone('utc'::text, now()),
  updated_at timestamp with time zone not null default timezone('utc'::text, now()),
  rating numeric default 0.0,
  rating_count integer default 0,
  is_favorite boolean default false,
  extras jsonb default '[]'::jsonb
);

-- orders
create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  table_id integer not null references public.tables(id),
  customer_name character varying,
  status character varying default 'active'::character varying,
  total_amount numeric default 0,
  created_at timestamp with time zone not null default timezone('utc'::text, now()),
  updated_at timestamp with time zone not null default timezone('utc'::text, now())
);

-- order_items
create table if not exists public.order_items (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.orders(id) on delete cascade,
  product_id integer not null references public.products(id),
  product_name character varying not null,
  price numeric not null,
  quantity integer default 1,
  notes text,
  status character varying default 'ordered'::character varying,
  created_at timestamp with time zone not null default timezone('utc'::text, now()),
  updated_at timestamp with time zone not null default timezone('utc'::text, now()),
  cancelled_quantity integer default 0
);

-- waiter_notifications
create table if not exists public.waiter_notifications (
  id uuid primary key default gen_random_uuid(),
  table_id integer not null references public.tables(id),
  order_id uuid references public.orders(id),
  type character varying not null,
  message text not null,
  status character varying default 'pending'::character varying,
  created_at timestamp with time zone not null default timezone('utc'::text, now()),
  updated_at timestamp with time zone default timezone('utc'::text, now()),
  payment_method character varying,
  tip_amount numeric default 0
);

-- sales_history
create table if not exists public.sales_history (
  id uuid primary key default gen_random_uuid(),
  table_id integer not null references public.tables(id),
  table_number integer not null,
  customer_name character varying,
  total_amount numeric not null default 0,
  order_count integer not null default 0,
  item_count integer not null default 0,
  created_at timestamp with time zone not null default timezone('utc'::text, now()),
  closed_at timestamp with time zone not null default timezone('utc'::text, now()),
  payment_method character varying
);

-- sales_items
create table if not exists public.sales_items (
  id uuid primary key default gen_random_uuid(),
  sale_id uuid not null references public.sales_history(id) on delete cascade,
  product_name character varying not null,
  price numeric not null,
  quantity integer not null default 1,
  subtotal numeric not null,
  notes text
);

-- customer_feedback
create table if not exists public.customer_feedback (
  id uuid primary key default gen_random_uuid(),
  table_id text not null,
  customer_name text not null,
  rating integer not null check (rating >= 1 and rating <= 5),
  comment text,
  order_count integer not null,
  total_amount numeric not null,
  created_at timestamp with time zone default now()
);

-- tips
create table if not exists public.tips (
  id uuid primary key default gen_random_uuid(),
  order_id uuid,
  table_id integer not null references public.tables(id) on delete cascade,
  customer_name text not null,
  amount numeric not null default 0,
  payment_method text,
  created_at timestamp with time zone not null default now()
);

-- ---------------------------------------------------------------------
-- Indices adicionales (fuera de PK/UNIQUE ya creados por las tablas)
-- ---------------------------------------------------------------------
create index if not exists tips_created_at_idx on public.tips using btree (created_at);
create index if not exists tips_table_id_idx on public.tips using btree (table_id);

-- ---------------------------------------------------------------------
-- Funciones
-- ---------------------------------------------------------------------
create or replace function public.update_updated_at_column()
returns trigger
language plpgsql
as $function$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$function$;

-- ---------------------------------------------------------------------
-- Row Level Security
-- ---------------------------------------------------------------------
alter table public.categories enable row level security;
alter table public.tables enable row level security;
alter table public.products enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;
alter table public.waiter_notifications enable row level security;
alter table public.sales_history enable row level security;
alter table public.sales_items enable row level security;
alter table public.customer_feedback enable row level security;
alter table public.tips enable row level security;

drop policy if exists "Allow all for all roles" on public.categories;
create policy "Allow all for all roles" on public.categories
  for all to public using (true) with check (true);

drop policy if exists "Allow all for tables" on public.tables;
create policy "Allow all for tables" on public.tables
  for all to public using (true);

drop policy if exists "Allow all for products" on public.products;
create policy "Allow all for products" on public.products
  for all to public using (true);

drop policy if exists "Allow all for orders" on public.orders;
create policy "Allow all for orders" on public.orders
  for all to public using (true);

drop policy if exists "Allow all for order_items" on public.order_items;
create policy "Allow all for order_items" on public.order_items
  for all to public using (true);

drop policy if exists "Allow all for notifications" on public.waiter_notifications;
create policy "Allow all for notifications" on public.waiter_notifications
  for all to public using (true);

drop policy if exists "Policy with security definer functions" on public.sales_history;
create policy "Policy with security definer functions" on public.sales_history
  for all to public using (true);

drop policy if exists "Policy with security definer functions" on public.sales_items;
create policy "Policy with security definer functions" on public.sales_items
  for all to public using (true);

drop policy if exists "feedback" on public.customer_feedback;
create policy "feedback" on public.customer_feedback
  for all to public using (true);

drop policy if exists "tips_select_all" on public.tips;
create policy "tips_select_all" on public.tips
  for select to public using (true);

drop policy if exists "tips_insert_all" on public.tips;
create policy "tips_insert_all" on public.tips
  for insert to public with check (true);

drop policy if exists "tips_update_all" on public.tips;
create policy "tips_update_all" on public.tips
  for update to public using (true);

-- ---------------------------------------------------------------------
-- Realtime publication
-- ---------------------------------------------------------------------
do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'tables'
  ) then
    alter publication supabase_realtime add table public.tables;
  end if;

  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'orders'
  ) then
    alter publication supabase_realtime add table public.orders;
  end if;

  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'order_items'
  ) then
    alter publication supabase_realtime add table public.order_items;
  end if;

  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'waiter_notifications'
  ) then
    alter publication supabase_realtime add table public.waiter_notifications;
  end if;
end $$;

-- ---------------------------------------------------------------------
-- Storage: buckets
-- ---------------------------------------------------------------------
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types, avif_autodetection)
values
  ('product-images', 'product-images', true, null, null, false),
  ('logo', 'logo', true, null, null, false),
  ('cover-image', 'cover-image', true, null, null, false)
on conflict (id) do nothing;

-- ---------------------------------------------------------------------
-- Storage: policies
-- ---------------------------------------------------------------------
drop policy if exists "Enable read access for all users" on storage.buckets;
create policy "Enable read access for all users" on storage.buckets
  for select to public using (true);

drop policy if exists "Enable read access for all users" on storage.objects;
create policy "Enable read access for all users" on storage.objects
  for insert to public with check (true);

drop policy if exists "Permitir lectura pública de logos" on storage.objects;
create policy "Permitir lectura pública de logos" on storage.objects
  for select to public using (bucket_id = 'logo'::text);

drop policy if exists "Permitir inserción de logos para usuarios autenticados" on storage.objects;
create policy "Permitir inserción de logos para usuarios autenticados" on storage.objects
  for insert to authenticated with check (bucket_id = 'logo'::text);

drop policy if exists "Permitir actualización de logos para usuarios autenticados" on storage.objects;
create policy "Permitir actualización de logos para usuarios autenticados" on storage.objects
  for update to authenticated using (bucket_id = 'logo'::text);

drop policy if exists "Permitir eliminación de logos para usuarios autenticados" on storage.objects;
create policy "Permitir eliminación de logos para usuarios autenticados" on storage.objects
  for delete to authenticated using (bucket_id = 'logo'::text);

drop policy if exists "Permitir lectura publica de cover-image" on storage.objects;
create policy "Permitir lectura publica de cover-image" on storage.objects
  for select to public using (bucket_id = 'cover-image'::text);

drop policy if exists "Permitir insercion de cover-image para usuarios autenticados" on storage.objects;
create policy "Permitir insercion de cover-image para usuarios autenticados" on storage.objects
  for insert to authenticated with check (bucket_id = 'cover-image'::text);

drop policy if exists "Permitir actualizacion de cover-image para usuarios autenticados" on storage.objects;
create policy "Permitir actualizacion de cover-image para usuarios autenticados" on storage.objects
  for update to authenticated using (bucket_id = 'cover-image'::text);

drop policy if exists "Permitir eliminacion de cover-image para usuarios autenticados" on storage.objects;
create policy "Permitir eliminacion de cover-image para usuarios autenticados" on storage.objects
  for delete to authenticated using (bucket_id = 'cover-image'::text);

commit;
