-- =====================================================================
-- FoodHub - Exportacion de estructura de base de datos (schema only)
-- Generado desde el proyecto Supabase de origen para replicar en otro
-- proyecto Supabase. No incluye datos, solo estructura.
--
-- TABLAS CON SUPABASE REALTIME (postgres_changes) — confirmado contra
-- pg_publication_tables del proyecto de origen, solo estas 4 tablas estan
-- agregadas a la publicacion supabase_realtime:
--   - tables          → Admin (TablesManagement), Waiter (dashboard)
--   - orders          → Admin (Dashboard), Waiter (dashboard)
--   - order_items     → Admin (Dashboard), Waiter (dashboard)
--   - waiter_notifications → Waiter (dashboard)
-- =====================================================================

begin;

-- ---------------------------------------------------------------------
-- Extensiones requeridas
-- ---------------------------------------------------------------------
create extension if not exists "uuid-ossp" with schema extensions;
create extension if not exists "pgcrypto" with schema extensions;

-- ---------------------------------------------------------------------
-- Tablas
-- ---------------------------------------------------------------------

-- categories
create table if not exists public.categories (
  id integer generated by default as identity primary key,
  name character varying not null,
  slug character varying not null unique,
  description text default ''::text,
  display_order integer default 0,
  is_active boolean default true,
  created_at timestamp with time zone default timezone('utc'::text, now()),
  updated_at timestamp with time zone default timezone('utc'::text, now())
);

-- tables
create table if not exists public.tables (
  id integer generated by default as identity primary key,
  number integer,
  status character varying default 'available'::character varying,
  capacity integer not null,
  location character varying,
  created_at timestamp with time zone not null default timezone('utc'::text, now()),
  updated_at timestamp with time zone not null default timezone('utc'::text, now())
);

-- products
create table if not exists public.products (
  id integer generated by default as identity primary key,
  name character varying not null,
  description text,
  price integer not null,
  category character varying not null,
  image_url character varying,
  is_available boolean default true,
  preparation_time integer,
  meal_type text not null default 'both'::text check (meal_type in ('breakfast', 'lunch', 'both')),
  created_at timestamp with time zone not null default timezone('utc'::text, now()),
  updated_at timestamp with time zone not null default timezone('utc'::text, now()),
  rating numeric default 0.0,
  rating_count integer default 0,
  is_favorite boolean default false,
  extras jsonb default '[]'::jsonb
);

-- orders
create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  table_id integer not null references public.tables(id),
  customer_name character varying,
  status character varying default 'active'::character varying,
  total_amount numeric default 0,
  created_at timestamp with time zone not null default timezone('utc'::text, now()),
  updated_at timestamp with time zone not null default timezone('utc'::text, now())
);

-- order_items
create table if not exists public.order_items (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.orders(id) on delete cascade,
  product_id integer not null references public.products(id),
  product_name character varying not null,
  price numeric not null,
  quantity integer default 1,
  notes text,
  status character varying default 'ordered'::character varying,
  created_at timestamp with time zone not null default timezone('utc'::text, now()),
  updated_at timestamp with time zone not null default timezone('utc'::text, now()),
  cancelled_quantity integer default 0,
  course smallint not null default 1 check (course >= 1 and course <= 3)
);

-- waiter_notifications
create table if not exists public.waiter_notifications (
  id uuid primary key default gen_random_uuid(),
  table_id integer not null references public.tables(id),
  order_id uuid references public.orders(id),
  type character varying not null,
  message text not null,
  status character varying default 'pending'::character varying,
  created_at timestamp with time zone not null default timezone('utc'::text, now()),
  updated_at timestamp with time zone default timezone('utc'::text, now()),
  payment_method character varying,
  tip_amount numeric default 0,
  tip_percentage numeric
);

comment on column public.waiter_notifications.tip_percentage is 'Porcentaje de propina elegido por el cliente en Payment.tsx: 0 = sin propina, 10/15/20 = boton de porcentaje, null = monto personalizado ("Otro"). El mesero solo puede VER esto, no modificarlo — lo usa PaymentCalculator (app/waiter/page.tsx) para resaltar el boton correcto en vez de mostrar siempre "Otro".';

-- sales_history
create table if not exists public.sales_history (
  id uuid primary key default gen_random_uuid(),
  table_id integer not null references public.tables(id),
  table_number integer not null,
  customer_name character varying,
  total_amount numeric not null default 0,
  order_count integer not null default 0,
  item_count integer not null default 0,
  created_at timestamp with time zone not null default timezone('utc'::text, now()),
  closed_at timestamp with time zone not null default timezone('utc'::text, now()),
  payment_method character varying,
  waiter_name text,
  payment_breakdown jsonb
);

-- sales_items
create table if not exists public.sales_items (
  id uuid primary key default gen_random_uuid(),
  sale_id uuid not null references public.sales_history(id) on delete cascade,
  product_name character varying not null,
  price numeric not null,
  quantity integer not null default 1,
  subtotal numeric not null,
  notes text
);

-- customer_feedback
create table if not exists public.customer_feedback (
  id uuid primary key default gen_random_uuid(),
  table_id text not null,
  customer_name text not null,
  rating integer not null check (rating >= 1 and rating <= 5),
  comment text,
  order_count integer not null,
  total_amount numeric not null,
  created_at timestamp with time zone default now(),
  feedback_type text not null default 'general' check (feedback_type in ('general', 'product')),
  product_id integer,
  product_name character varying
);

-- tips
create table if not exists public.tips (
  id uuid primary key default gen_random_uuid(),
  order_id uuid,
  table_id integer not null references public.tables(id) on delete cascade,
  customer_name text not null,
  amount numeric not null default 0,
  payment_method text,
  payment_breakdown jsonb,
  waiter_id uuid references public.users(id) on delete set null,
  created_at timestamp with time zone not null default now()
);

comment on column public.customer_feedback.feedback_type is 'general = overall service review, product = review of a single ordered item';
comment on column public.customer_feedback.product_id is 'Only set when feedback_type = product. No FK to keep historical feedback intact if the product is later deleted.';
comment on column public.customer_feedback.product_name is 'Snapshot of the product name at review time, only set when feedback_type = product.';

comment on column public.sales_history.payment_breakdown is 'Solo cuando payment_method=mixed: {cash, terminal, usd} en MXN, neto de cambio (se asume que el cambio sale de la parte en efectivo). Usado por cash_reports para saber cuanto de una venta mixta fue efectivo real.';
comment on column public.tips.payment_breakdown is 'Igual que sales_history.payment_breakdown, para propinas pagadas con payment_method=mixed.';

-- users: cuentas de staff (admin / waiter / super_admin) vinculadas a auth.users.
-- El rol de autorizacion vive en auth.users.raw_app_meta_data (JWT app_metadata),
-- no en esta tabla, para permitir checks de rol sin round-trip a public.users.
create table if not exists public.users (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null unique,
  name text not null,
  role text not null check (role in ('super_admin', 'admin', 'waiter')),
  pin_code char(4),
  is_active boolean not null default true,
  created_at timestamp with time zone not null default timezone('utc'::text, now()),
  updated_at timestamp with time zone not null default timezone('utc'::text, now()),
  constraint users_pin_code_format check (pin_code is null or pin_code ~ '^[0-9]{4}$')
);

-- app_settings: feature flags opt-in/opt-out configurables desde el admin panel
-- Soporta boolean (toggles) y text (time, select).
-- Lectura publica (el customer sin login necesita leer los flags),
-- escritura solo admin/super_admin.
create table if not exists public.app_settings (
  key text primary key,
  value text not null default 'false',
  updated_at timestamp with time zone not null default timezone('utc', now())
);

-- waiter_sessions: rastreo de turno por mesero para cierre y distribucion de propinas
create table if not exists public.waiter_sessions (
  id uuid primary key default gen_random_uuid(),
  waiter_id uuid not null references public.users(id) on delete cascade,
  waiter_name text not null,
  started_at timestamptz not null default now(),
  ended_at timestamptz,
  total_sales numeric not null default 0,
  tips_collected numeric not null default 0,
  tips_paid_out numeric not null default 0,
  tip_distribution_snapshot jsonb,
  created_at timestamptz not null default now()
);

comment on column public.waiter_sessions.tips_collected is 'Snapshot: total de propinas de la sesion (todas las formas de pago) al momento de cerrar turno.';
comment on column public.waiter_sessions.tips_paid_out is 'Monto realmente entregado en el reparto de propinas al cerrar turno = tips_collected * (suma de porcentajes de tip_distribution_snapshot) / 100. Esto es lo que cash_reports.tips_paid usa para calcular expected_cash (sale fisicamente de la caja).';
comment on column public.waiter_sessions.tip_distribution_snapshot is 'Copia de app_settings.tip_distribution usada en este cierre de turno, para trazabilidad si el admin cambia los porcentajes despues.';

-- cash_reports: sesion de caja abierta/cerrada (patron started_at/ended_at,
-- igual que waiter_sessions). "Abierta" = closed_at is null. Snapshot de
-- ventas/propinas del periodo [opened_at, closed_at] calculado al cerrar.
create table if not exists public.cash_reports (
  id uuid primary key default gen_random_uuid(),
  report_number integer generated always as identity,
  opened_at timestamp with time zone not null default now(),
  closed_at timestamp with time zone,

  opening_cash numeric not null default 0,
  cash_deposits numeric not null default 0,
  cash_withdrawals numeric not null default 0,
  counted_cash numeric,
  notes text,

  cash_sales numeric not null default 0,
  terminal_sales numeric not null default 0,
  usd_sales numeric not null default 0,
  total_sales numeric not null default 0,

  cash_tips numeric not null default 0,
  terminal_tips numeric not null default 0,
  usd_tips numeric not null default 0,
  total_tips numeric not null default 0,

  paid_accounts_count integer not null default 0,
  average_ticket numeric not null default 0,
  subtotal numeric not null default 0,
  tax_amount numeric not null default 0,
  tax_rate numeric not null default 16,
  tips_paid numeric not null default 0,

  expected_cash numeric not null default 0,
  cash_difference numeric not null default 0,

  opened_by uuid references public.users(id) on delete set null,
  closed_by uuid references public.users(id) on delete set null,
  created_at timestamp with time zone not null default now()
);

comment on table public.cash_reports is 'Corte de caja diario: snapshot de ventas/propinas del día + reconciliación manual de efectivo (entrada del cajero).';
comment on column public.cash_reports.opened_at is 'Momento en que el cajero abrió la caja (inicio del período que cubre el reporte).';
comment on column public.cash_reports.closed_at is 'Momento en que el cajero cerró la caja. NULL mientras la caja está abierta (solo puede haber una fila con closed_at NULL a la vez).';
comment on column public.cash_reports.cash_deposits is 'Calculado al cerrar: suma de efectivo bruto entregado por clientes (antes de dar cambio) en el periodo, leido de payment_breakdown.cashTendered.';
comment on column public.cash_reports.cash_withdrawals is 'Calculado al cerrar: suma del cambio entregado a clientes en el periodo, leido de payment_breakdown.change.';
comment on column public.cash_reports.tax_rate is 'Tasa de IVA (%) usada para este reporte, tomada de app_settings.iva_rate al momento de cerrar la caja (snapshot, no cambia si el setting cambia despues).';
comment on column public.cash_reports.tips_paid is 'Propinas pagadas: suma de waiter_sessions.tips_paid_out para sesiones cuyo ended_at cae en [opened_at, closed_at] del corte de caja. Usado en expected_cash y en la seccion CAJA del ticket. Distinto de cash_tips/terminal_tips/usd_tips/total_tips, que son propinas RECIBIDAS (informativo, seccion FORMA DE PAGO PROPINA).';

-- cash_sales/terminal_sales/usd_sales (y su equivalente _tips) reparten cada
-- cobro/propina 'mixed' usando payment_breakdown, asi que siempre suman
-- exactamente total_sales/total_tips: no hace falta una columna "mixed" aparte.

-- cash_tips/terminal_tips/usd_tips/total_tips = propinas RECIBIDAS (informativo,
-- seccion "Forma de pago propina"). tips_paid = suma de tip_payouts.amount
-- (pagos REALMENTE marcados como pagados en la pestana Propinas del admin) en
-- el periodo del corte — es lo que realmente sale de la caja y se usa en
-- expected_cash. Son conceptos distintos y pueden no coincidir (propina
-- recibida hoy, pago marcado dias despues).

-- tip_ledger_entries: acumulacion de dinero por repartir de propinas, una fila
-- por (cierre de turno x destinatario). recipient_type='role' para Barra/
-- Cocina/etc (recipient_key=nombre del rol de app_settings.tip_distribution),
-- recipient_type='waiter' para lo que se le debe a un mesero por propinas en
-- tarjeta/dolares que no recibio en efectivo (recipient_key=users.id).
create table if not exists public.tip_ledger_entries (
  id uuid primary key default gen_random_uuid(),
  waiter_session_id uuid references public.waiter_sessions(id) on delete set null,
  recipient_type text not null check (recipient_type in ('waiter','role')),
  recipient_key text not null,
  recipient_name text not null,
  amount numeric not null default 0,
  created_at timestamptz not null default now()
);

-- tip_payouts: eventos de pago real (cuando un admin marca como pagado el
-- saldo, parcial o total, de un destinatario). Saldo pendiente de un
-- destinatario = SUM(tip_ledger_entries.amount) - SUM(tip_payouts.amount)
-- agrupado por (recipient_type, recipient_key) — modelo tipo "cuenta
-- corriente", sin ligar pagos a acumulaciones especificas.
create table if not exists public.tip_payouts (
  id uuid primary key default gen_random_uuid(),
  recipient_type text not null check (recipient_type in ('waiter','role')),
  recipient_key text not null,
  recipient_name text not null,
  amount numeric not null default 0,
  paid_at timestamptz not null default now(),
  paid_by uuid references public.users(id) on delete set null,
  notes text,
  created_at timestamptz not null default now()
);

comment on table public.tip_ledger_entries is 'Acumulacion de dinero por repartir de propinas: una fila por (cierre de turno x destinatario). El saldo pendiente de un destinatario = SUM(tip_ledger_entries.amount) - SUM(tip_payouts.amount).';
comment on table public.tip_payouts is 'Eventos de pago real: cuando un admin marca como pagado el saldo (parcial o total) de un destinatario. Solo estos montos, dentro del periodo del corte de caja, cuentan como cash_reports.tips_paid — mientras no este pagado, el dinero sigue fisicamente en la caja.';

-- table_waiter_assignments: asignacion de mesero a mesa por el cliente
create table if not exists public.table_waiter_assignments (
  id bigint generated always as identity primary key,
  table_id bigint not null references public.tables(id),
  waiter_id uuid not null,
  waiter_name text not null,
  assigned_at timestamptz default now()
);

-- ---------------------------------------------------------------------
-- Indices adicionales (fuera de PK/UNIQUE ya creados por las tablas)
-- ---------------------------------------------------------------------
create index if not exists tips_created_at_idx on public.tips using btree (created_at);
create index if not exists tips_table_id_idx on public.tips using btree (table_id);
create index if not exists tips_waiter_id_idx on public.tips using btree (waiter_id);

create index if not exists waiter_sessions_waiter_id_idx on public.waiter_sessions (waiter_id);
create index if not exists waiter_sessions_started_at_idx on public.waiter_sessions (started_at);

create index if not exists tip_ledger_entries_recipient_idx on public.tip_ledger_entries (recipient_type, recipient_key);
create index if not exists tip_payouts_recipient_idx on public.tip_payouts (recipient_type, recipient_key);
create index if not exists tip_payouts_paid_at_idx on public.tip_payouts (paid_at);

-- Unico PIN activo a la vez: permite reciclar el PIN de un waiter desactivado.
create unique index if not exists users_pin_code_unique_idx
  on public.users (pin_code)
  where pin_code is not null and is_active = true;
create index if not exists users_role_idx on public.users (role);

-- Solo una caja abierta a la vez.
create unique index if not exists cash_reports_single_open_idx
  on public.cash_reports ((closed_at is null))
  where closed_at is null;

-- ---------------------------------------------------------------------
-- Funciones
-- ---------------------------------------------------------------------
create or replace function public.update_updated_at_column()
returns trigger
language plpgsql
as $function$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$function$;

drop trigger if exists set_users_updated_at on public.users;
create trigger set_users_updated_at
  before update on public.users
  for each row execute function public.update_updated_at_column();

drop trigger if exists set_app_settings_updated_at on public.app_settings;
create trigger set_app_settings_updated_at
  before update on public.app_settings
  for each row execute function public.update_updated_at_column();

-- Lee app_metadata.role directo del JWT (sin consultar public.users -> sin recursion RLS)
create or replace function public.current_role()
returns text
language sql
stable
set search_path = ''
as $function$
  select coalesce((auth.jwt() -> 'app_metadata' ->> 'role'), '');
$function$;

-- ---------------------------------------------------------------------
-- Row Level Security
-- ---------------------------------------------------------------------
alter table public.categories enable row level security;
alter table public.tables enable row level security;
alter table public.products enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;
alter table public.waiter_notifications enable row level security;
alter table public.sales_history enable row level security;
alter table public.sales_items enable row level security;
alter table public.customer_feedback enable row level security;
alter table public.tips enable row level security;
alter table public.users enable row level security;
alter table public.waiter_sessions enable row level security;
alter table public.table_waiter_assignments enable row level security;
alter table public.app_settings enable row level security;
alter table public.cash_reports enable row level security;
alter table public.tip_ledger_entries enable row level security;
alter table public.tip_payouts enable row level security;

drop policy if exists "Allow all for all roles" on public.categories;
create policy "Allow all for all roles" on public.categories
  for all to public using (true) with check (true);

drop policy if exists "Allow all for tables" on public.tables;
create policy "Allow all for tables" on public.tables
  for all to public using (true);

drop policy if exists "Allow all for products" on public.products;
create policy "Allow all for products" on public.products
  for all to public using (true);

drop policy if exists "Allow all for orders" on public.orders;
create policy "Allow all for orders" on public.orders
  for all to public using (true);

drop policy if exists "Allow all for order_items" on public.order_items;
create policy "Allow all for order_items" on public.order_items
  for all to public using (true);

drop policy if exists "Allow all for notifications" on public.waiter_notifications;
create policy "Allow all for notifications" on public.waiter_notifications
  for all to public using (true);

drop policy if exists "Policy with security definer functions" on public.sales_history;
create policy "Policy with security definer functions" on public.sales_history
  for all to public using (true);

drop policy if exists "Policy with security definer functions" on public.sales_items;
create policy "Policy with security definer functions" on public.sales_items
  for all to public using (true);

drop policy if exists "feedback" on public.customer_feedback;
create policy "feedback" on public.customer_feedback
  for all to public using (true);

drop policy if exists "tips_select_all" on public.tips;
create policy "tips_select_all" on public.tips
  for select to public using (true);

drop policy if exists "tips_insert_all" on public.tips;
create policy "tips_insert_all" on public.tips
  for insert to public with check (true);

drop policy if exists "tips_update_all" on public.tips;
create policy "tips_update_all" on public.tips
  for update to public using (true);

-- users: unica tabla con RLS real por rol (el resto queda "allow all" por ahora)
drop policy if exists "users_select" on public.users;
create policy "users_select" on public.users
  for select to authenticated
  using (id = auth.uid() or public.current_role() in ('admin', 'super_admin'));

drop policy if exists "users_insert" on public.users;
create policy "users_insert" on public.users
  for insert to authenticated
  with check (public.current_role() in ('admin', 'super_admin'));

drop policy if exists "users_update" on public.users;
create policy "users_update" on public.users
  for update to authenticated
  using (public.current_role() in ('admin', 'super_admin'))
  with check (public.current_role() in ('admin', 'super_admin'));

drop policy if exists "users_delete" on public.users;
create policy "users_delete" on public.users
  for delete to authenticated
  using (public.current_role() in ('admin', 'super_admin'));

drop policy if exists "Allow all for waiter_sessions" on public.waiter_sessions;
create policy "Allow all for waiter_sessions" on public.waiter_sessions
  for all to public using (true);

drop policy if exists "Allow all for cash_reports" on public.cash_reports;
create policy "Allow all for cash_reports" on public.cash_reports
  for all to public using (true);
drop policy if exists "Allow all for tip_ledger_entries" on public.tip_ledger_entries;
create policy "Allow all for tip_ledger_entries" on public.tip_ledger_entries
  for all using (true) with check (true);
drop policy if exists "Allow all for tip_payouts" on public.tip_payouts;
create policy "Allow all for tip_payouts" on public.tip_payouts
  for all using (true) with check (true);
drop policy if exists "Anyone can read table_waiter_assignments" on public.table_waiter_assignments;
create policy "Anyone can read table_waiter_assignments" on public.table_waiter_assignments
  for select to public using (true);

drop policy if exists "Anyone can insert table_waiter_assignments" on public.table_waiter_assignments;
create policy "Anyone can insert table_waiter_assignments" on public.table_waiter_assignments
  for insert to public with check (true);

drop policy if exists "Anyone can delete table_waiter_assignments" on public.table_waiter_assignments;
create policy "Anyone can delete table_waiter_assignments" on public.table_waiter_assignments
  for delete to public using (true);

-- app_settings: lectura publica (customer sin login la necesita), escritura solo admin
drop policy if exists "app_settings_select_public" on public.app_settings;
create policy "app_settings_select_public" on public.app_settings
  for select to public using (true);

drop policy if exists "app_settings_write_admin" on public.app_settings;
create policy "app_settings_write_admin" on public.app_settings
  for all to authenticated
  using (public.current_role() in ('admin', 'super_admin'))
  with check (public.current_role() in ('admin', 'super_admin'));

-- ---------------------------------------------------------------------
-- Realtime publication
-- ---------------------------------------------------------------------
do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'tables'
  ) then
    alter publication supabase_realtime add table public.tables;
  end if;

  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'orders'
  ) then
    alter publication supabase_realtime add table public.orders;
  end if;

  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'order_items'
  ) then
    alter publication supabase_realtime add table public.order_items;
  end if;

  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'waiter_notifications'
  ) then
    alter publication supabase_realtime add table public.waiter_notifications;
  end if;
end $$;

-- ---------------------------------------------------------------------
-- Migraciones aplicadas
-- ---------------------------------------------------------------------

-- 2026-07-20: add_meal_type_to_products
-- Agrega columna meal_type a products para controlar visibilidad por horario
alter table public.products add column if not exists meal_type text not null default 'both'::text
  check (meal_type in ('breakfast', 'lunch', 'both'));

update public.products set meal_type = 'breakfast' where category = 'Breakfast' and meal_type = 'both';
update public.products set meal_type = 'lunch' where category in ('Lunch', 'Dinner') and meal_type = 'both';
update public.products set meal_type = 'both' where category in ('Combos', 'Drinks', 'Refill') and meal_type = 'both';

-- 2026-07-20: Alter app_settings.value a text para soportar string ademas de boolean
alter table public.app_settings alter column value type text using value::text;
alter table public.app_settings alter column value set not null;
alter table public.app_settings alter column value set default 'false'::text;

-- 2026-07-21: add_course_to_order_items
-- Agrega columna course a order_items para tiempos de comida (1=Primer, 2=Segundo, 3=Tercer)
alter table public.order_items add column if not exists course smallint not null default 1
  check (course >= 1 and course <= 3);

-- 2026-07-21: add_feedback_type_to_customer_feedback
-- Distingue reseñas generales de reseñas por producto en la encuesta post-pago
alter table public.customer_feedback
  add column if not exists feedback_type text not null default 'general' check (feedback_type in ('general', 'product'));
alter table public.customer_feedback
  add column if not exists product_id integer;
alter table public.customer_feedback
  add column if not exists product_name character varying;

-- 2026-07-21: add_waiter_sessions
-- Tabla + columna waiter_id en tips + indices + seed ya incluidos arriba.
-- Migration aplicada: creacion de waiter_sessions, tips.waiter_id, indices y seed tip_distribution.
-- 2026-07-21: add_tips_waiter_id
-- 2026-07-21: add_waiter_sessions_indexes

-- 2026-07-22: create_cash_reports_table
-- Tabla cash_reports (corte de caja diario) ya incluida arriba.

-- 2026-07-22: cash_reports_open_close_flow
-- Rediseno de "un reporte por fecha con inputs manuales" a sesion abierta/cerrada
-- (opened_at/closed_at, "abierta" = closed_at is null). Se eliminan report_date,
-- cash_deposits, cash_withdrawals (sin dato real detras); created_by -> opened_by;
-- se agrega closed_by. Cambios ya incluidos en la definicion de la tabla arriba.

-- 2026-07-22: add_payment_breakdown_for_mixed_payments
-- Columna payment_breakdown jsonb en sales_history y tips (solo se llena cuando
-- payment_method='mixed'): {cash, terminal, usd} en MXN. cash_reports usa el
-- desglose para saber cuanto de un cobro mixto fue efectivo real, en vez de
-- excluir esas cuentas del calculo de caja.

-- 2026-07-22: drop_mixed_columns_from_cash_reports
-- Se eliminan cash_reports.mixed_sales y mixed_tips: eran solo informativos y
-- redundantes, ya que cash_sales/terminal_sales/usd_sales (via payment_breakdown)
-- ya reparten los cobros/propinas mixtos por completo.

-- 2026-07-22: add_cash_deposits_withdrawals_computed
-- Regresan cash_reports.cash_deposits/cash_withdrawals (se habian quitado antes
-- por ser inputs manuales sin dato real detras). Ahora se calculan solos al
-- cerrar la caja: cash_deposits = suma de payment_breakdown.cashTendered
-- (efectivo bruto entregado), cash_withdrawals = suma de payment_breakdown.change
-- (cambio devuelto). Formula de expected_cash actualizada:
-- opening_cash + cash_deposits - cash_withdrawals - cash_tips.

-- 2026-07-22: add_tax_rate_snapshot_to_cash_reports
-- Columna cash_reports.tax_rate numeric not null default 16. Antes subtotal/
-- tax_amount se calculaban con un 16% hardcodeado; ahora se lee
-- app_settings.iva_rate (mismo setting que SettingsManagement.tsx expone en
-- "IVA y tipo de cambio", ya usado por Payment.tsx/Menu.tsx del lado cliente)
-- al momento de cerrar la caja, y se guarda el valor usado en tax_rate como
-- snapshot (un reporte cerrado no cambia si el admin edita iva_rate despues).
-- Cae a 16 por defecto si el setting falta o no es numerico.

-- 2026-07-22: add_tip_payout_snapshot_to_waiter_sessions
-- Columnas waiter_sessions.tips_collected/tips_paid_out numeric not null
-- default 0, tip_distribution_snapshot jsonb. Persisten el reparto de
-- propinas al cerrar turno (sessionsService.endSession()) — antes
-- EndShiftModal.tsx solo lo calculaba para mostrarlo y se descartaba.
-- tips_paid_out = tips_collected * (suma de % de tip_distribution_snapshot) / 100.

-- 2026-07-22: add_tips_paid_to_cash_reports
-- Columna cash_reports.tips_paid numeric not null default 0: suma de
-- waiter_sessions.tips_paid_out para sesiones con ended_at en
-- [opened_at, closed_at] del corte. Corrige el uso anterior de cash_tips
-- (propinas RECIBIDAS) en "Propinas pagadas" y en expected_cash — la propina
-- en efectivo sigue fisicamente en la caja hasta que se reparte al cerrar
-- turno, no en el momento en que se cobra. Formula actualizada:
-- expected_cash = opening_cash + cash_deposits - cash_withdrawals - tips_paid.

-- 2026-07-22: create_tip_ledger_and_payouts
-- Tablas nuevas tip_ledger_entries (acumulacion al cerrar turno) y tip_payouts
-- (pago real marcado desde la pestana Propinas del admin). Corrige la
-- migracion anterior (add_tips_paid_to_cash_reports): lo acumulado al cerrar
-- turno (waiter_sessions.tips_paid_out) TAMPOCO sale de la caja en ese
-- momento — sigue fisicamente ahi hasta que alguien lo entrega de verdad.
-- cash_reports.tips_paid pasa a sumar tip_payouts.amount (con paid_at en el
-- periodo del corte) en vez de tips_paid_out. sessionsService.endSession()
-- ahora inserta en tip_ledger_entries: una fila por rol de tip_distribution
-- con pct>0, y una fila para el mesero si el efectivo que trae no alcanza a
-- cubrir su propina en tarjeta/dolares (lo que se le debe). Saldo pendiente
-- de un destinatario = SUM(tip_ledger_entries.amount) - SUM(tip_payouts.amount).

-- 2026-07-23: add_tip_percentage_to_waiter_notifications
-- Columna waiter_notifications.tip_percentage numeric (nullable). Antes solo
-- se guardaba tip_amount (el monto en pesos), asi que la vista del mesero no
-- podia saber si el cliente eligio un boton de % o un monto personalizado y
-- siempre mostraba "Otro". Ahora Payment.tsx guarda tambien tip_percentage
-- (0=sin propina, 10/15/20=boton de %, null=personalizado) y el mesero lo usa
-- solo para mostrar/resaltar la seleccion — no puede modificarla, la propina
-- la define unicamente el cliente desde su pantalla de pago.

-- 2026-07-28: add_waiter_name_to_sales_history
-- Columna sales_history.waiter_name text (nullable). Guarda el nombre del
-- mesero que atendio la mesa al momento de cerrarla, para el reporte de
-- propinas por mesero (WaiterReportTips / TipsTab).

-- ---------------------------------------------------------------------
-- Seed data: feature flags iniciales
-- ---------------------------------------------------------------------
insert into public.app_settings (key, value)
values ('product_notes_enabled', 'false')
on conflict (key) do nothing;

insert into public.app_settings (key, value)
values ('product_ratings_enabled', 'false')
on conflict (key) do nothing;

insert into public.app_settings (key, value)
values ('breakfast_end_hour', '11:00')
on conflict (key) do nothing;

insert into public.app_settings (key, value)
values ('printing_enabled', 'false')
on conflict (key) do nothing;

insert into public.app_settings (key, value)
values ('default_check_ui', 'modern')
on conflict (key) do nothing;

insert into public.app_settings (key, value)
values ('close_table_pin', '1234')
on conflict (key) do nothing;

insert into public.app_settings (key, value)
values ('tip_distribution', '{"Barra":1.2,"Cocina":3.0,"Garrotero":0,"Capitan":0,"Staff":1.0,"Caja":1.2,"Empaque":0}')
on conflict (key) do nothing;

-- ---------------------------------------------------------------------
-- Seed data: datos del negocio, IVA/tipo de cambio y personalizacion del
-- ticket/pasos del pedido (app_settings.key adicionales, agregados via
-- SettingsManagement.tsx en el admin; no estaban en el seed original).
-- ---------------------------------------------------------------------
insert into public.app_settings (key, value)
values ('business_name', 'RioChia7')
on conflict (key) do nothing;

insert into public.app_settings (key, value)
values ('business_owner', 'ELDA CABRERA VERA')
on conflict (key) do nothing;

insert into public.app_settings (key, value)
values ('business_rfc', 'CAVE6102187H1')
on conflict (key) do nothing;

insert into public.app_settings (key, value)
values ('business_address', 'Independencia Num. 6213, Col. Castillo, Tijuana, Baja California, México CP 22050')
on conflict (key) do nothing;

insert into public.app_settings (key, value)
values ('business_sucursal', 'Independencia Num. 6213, Col. Castillo, Tijuana, B.C.')
on conflict (key) do nothing;

insert into public.app_settings (key, value)
values ('iva_rate', '16')
on conflict (key) do nothing;

insert into public.app_settings (key, value)
values ('usd_rate', '19.5')
on conflict (key) do nothing;

insert into public.app_settings (key, value)
values ('order_steps', $$ {"ordered":{"label":"Ordenado","shortLabel":"Ord.","color":"var(--red)","bg":"var(--red-light)","icon":"●","next":"preparing"},"preparing":{"label":"En preparación","shortLabel":"Prep.","color":"var(--amber)","bg":"oklch(96% 0.06 70)","icon":"⏳","next":"ready"},"ready":{"label":"Listo","shortLabel":"Listo","color":"var(--blue)","bg":"var(--blue-light)","icon":"✓","next":"served"},"served":{"label":"Servido","shortLabel":"Serv.","color":"var(--green)","bg":"var(--green-light)","icon":"✓","next":"served"},"cancelled":{"label":"Cancelado","shortLabel":"Canc.","color":"var(--muted)","bg":"var(--surface)","icon":"✕","next":"cancelled"}} $$)
on conflict (key) do nothing;

insert into public.app_settings (key, value)
values ('check_ui_customization', $$ {"modern":{"containerBg":"#ffffff","containerBorder":"solid","containerRadius":"large","spacing":"normal","headerColor":"#ffffff","headerBg":"oklch(22% 0.04 260)","accentColor":"oklch(20% 0.02 260)","fontFamily":"sans","footerText":"GRACIAS POR SU PREFERENCIA","footerColor":"oklch(52% 0.16 145)"},"classic":{"containerBg":"oklch(98.5% 0.005 80)","containerBorder":"dotted","containerRadius":"small","spacing":"normal","headerColor":"oklch(62% 0.18 32)","headerBg":"transparent","accentColor":"oklch(62% 0.18 32)","fontFamily":"serif","footerText":"GRACIAS POR SU PREFERENCIA","footerColor":"oklch(62% 0.18 32)"},"compact":{"containerBg":"#ffffff","containerBorder":"solid","containerRadius":"medium","spacing":"compact","headerColor":"oklch(22% 0.04 260)","headerBg":"transparent","accentColor":"oklch(20% 0.02 260)","fontFamily":"sans","footerText":"GRACIAS POR SU PREFERENCIA","footerColor":"oklch(55% 0.02 260)"}} $$)
on conflict (key) do nothing;

-- ---------------------------------------------------------------------
-- Storage: buckets
-- ---------------------------------------------------------------------
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types, avif_autodetection)
values
  ('product-images', 'product-images', true, null, null, false),
  ('logo', 'logo', true, null, null, false),
  ('cover-image', 'cover-image', true, null, null, false)
on conflict (id) do nothing;

-- ---------------------------------------------------------------------
-- Storage: policies
-- ---------------------------------------------------------------------
drop policy if exists "Enable read access for all users" on storage.buckets;
create policy "Enable read access for all users" on storage.buckets
  for select to public using (true);

drop policy if exists "Enable read access for all users" on storage.objects;
create policy "Enable read access for all users" on storage.objects
  for insert to public with check (true);

drop policy if exists "Permitir lectura pública de logos" on storage.objects;
create policy "Permitir lectura pública de logos" on storage.objects
  for select to public using (bucket_id = 'logo'::text);

drop policy if exists "Permitir inserción de logos para usuarios autenticados" on storage.objects;
create policy "Permitir inserción de logos para usuarios autenticados" on storage.objects
  for insert to authenticated with check (bucket_id = 'logo'::text);

drop policy if exists "Permitir actualización de logos para usuarios autenticados" on storage.objects;
create policy "Permitir actualización de logos para usuarios autenticados" on storage.objects
  for update to authenticated using (bucket_id = 'logo'::text);

drop policy if exists "Permitir eliminación de logos para usuarios autenticados" on storage.objects;
create policy "Permitir eliminación de logos para usuarios autenticados" on storage.objects
  for delete to authenticated using (bucket_id = 'logo'::text);

drop policy if exists "Permitir lectura publica de cover-image" on storage.objects;
create policy "Permitir lectura publica de cover-image" on storage.objects
  for select to public using (bucket_id = 'cover-image'::text);

drop policy if exists "Permitir insercion de cover-image para usuarios autenticados" on storage.objects;
create policy "Permitir insercion de cover-image para usuarios autenticados" on storage.objects
  for insert to authenticated with check (bucket_id = 'cover-image'::text);

-- Nota: el nombre real de esta policy en el proyecto de origen quedo sin la
-- "s" final ("autenticado", no "autenticados") por un typo original; se deja
-- igual aqui para que el drop/create de arriba coincida con la policy real.
drop policy if exists "Permitir actualizacion de cover-image para usuarios autenticado" on storage.objects;
create policy "Permitir actualizacion de cover-image para usuarios autenticado" on storage.objects
  for update to authenticated using (bucket_id = 'cover-image'::text);

drop policy if exists "Permitir eliminacion de cover-image para usuarios autenticados" on storage.objects;
create policy "Permitir eliminacion de cover-image para usuarios autenticados" on storage.objects
  for delete to authenticated using (bucket_id = 'cover-image'::text);

commit;
